import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Passeport Cegid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          height: "100vh",
          alignItems: "center",
          backgroundColor: "gray",
          color: "white",
        }}
      >
        <h1>Signin Page Passeport</h1>
        <Link href="/signin/profile"> Send </Link>
        <h3>The user has to confirm the password</h3>
        <button onClick={() => alert("The information has been sent")}>
          Send new password
        </button>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  return {
    props: {}, // will be passed to the page component as props
  };
}

export default Home;
