import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Passeport Cegid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          height: "100vh",
          alignItems: "center",
          backgroundColor: "gray",
          color: "white",
        }}
      >
        <h1>Signin Page Passeport</h1>
        <h2>Token Validation</h2>
        <h3>The user has to type the token received by email</h3>
        <button onClick={() => alert("The information has been sent")}>
          Send Token
        </button>
      </div>
    </div>
  );
};

export default Home;
